### ISSUE TITLE
Broken link: https://docs.dappnode.io/get-started/installation/custom-hardware/installation/overview/iso

### ISSUE THREAD

**Issue by manprinsen** [dappnode/DAppNodeDocs#112]
**Describe the bug**
Broken link: https://docs.dappnode.io/get-started/installation/custom-hardware/installation/overview/iso

**Comment by tropicar** [comment]
Did you access that link from https://docs.dappnode.io/get-started/installation/custom-hardware/installation/overview clicking on  Installing with an ISO or from where?

**Comment by tropicar** [comment]
I have replace this links for full paths, so the issue should not happen again. Thank you very much for the feedback
