### ISSUE TITLE
Invalid links for script/ISO on Installation Overview

### ISSUE THREAD

**Issue by JuanuMusic** [dappnode/DAppNodeDocs#114]
**Describe the bug**

Both links to "Installing with a script" and "Installing with an ISO" on the [overview page](https://docs.dappnode.io/get-started/installation/custom-hardware/installation/overview/) are broken. Links from the menu still work

**To Reproduce**

1. Navigate to https://docs.dappnode.io/get-started/installation/custom-hardware/installation/overview/
2. Click on "Installing with a script" or on "Installing with an ISO"
3. Page not found error is shown

**Expected behavior**

Should redirect to the correct pages which work from the menu:
- Installing with an ISO should link to https://docs.dappnode.io/get-started/installation/custom-hardware/installation/iso
- Installing with a script should link to https://docs.dappnode.io/get-started/installation/custom-hardware/installation/script

**Comment by tropicar** [comment]
It's fixed. Thank you for the feedback!!
