### ISSUE TITLE
Add docs for docker-compose whitelisted keys

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodeDocs#139]
## Context
When developing a DAppNode package, not all docker-compose keys are supported, there is a `parseSafeCompose` function in the dappmanagfer that uses whitelisted keys to be used. 

## Feature request
Consider adding documentation for this whitelisted keys, especially useful for developers.
Take into account this issue https://github.com/dappnode/DNP_DAPPMANAGER/issues/978

**Comment by dapplion** [comment]
Really necessary!

**Comment by tropicar** [comment]
Done
