### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by caviar2** [dappnode/DAppNodeDocs#153]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by alexpeterson91** [comment]
Please actually fill out all relevant info from the template and also just "bug" is not at all helpful. What's wrong? Explain in detail with screenshots and background info. How you're accessing the docs what browser what OS? So on and so forth. Will be closing the issue in a day if it's not updated.
