### ISSUE TITLE
Broken link !important

### ISSUE THREAD

**Issue by jeanandrev** [dappnode/DAppNodeDocs#159]
**Describe the bug**

As a first-time user, I need to follow the recommended "First steps..." However, the link is broken.

**To Reproduce**

From https://docs.dappnode.io/get-started/installation/dappnode-hardware/installation/
Click on https://docs.dappnode.io/get-started/first-steps

**Expected behavior**

To display the first steps on how to configure my DAppNode

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by tropicar** [comment]
The origin url ends with a slash "/", I don't know how to arrive at that URL. The normal would be to go to https://docs.dappnode.io/get-started/installation/dappnode-hardware/installation , if you can tell exactly how you come to that URL exactly, it would be nice to try to fix it. Thanks for reporting it.
