### ISSUE TITLE
Give feedback after user testing / unboxing

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNodeDocs#165]
Doing a DAppNode unboxing and documenting all friction points.
- What are the friction points?
- What can be improved at packaging level?
- What can be improved at documentation level?
- How can we make it easier for the user?

**Comment by clarawasabi** [comment]
incluir código qr para ir a la página de welcome
Mejorar pag de welcome  (Yuki)
En las instrucciones no se indica que hay que conectarlo a la luz 
Incluir en las instrucciones el contenido de la caja

**Comment by clarawasabi** [comment]
![ad3772c3-76ad-4a05-a563-826c681b29f8](https://user-images.githubusercontent.com/104911883/169000354-3d56502b-0480-41f0-a0ec-164d1dec0c66.jpeg)

**Comment by clarawasabi** [comment]
<img width="753" alt="Captura de pantalla 2022-05-18 a las 10 32 53" src="https://user-images.githubusercontent.com/104911883/169000428-dc9b3584-e65c-4d6a-9893-ef45b318455c.png">

**Comment by tropicar** [comment]
If this issue is completed, I will mark it as done.
