### ISSUE TITLE
faulty redirect from iso.dappnode.io

### ISSUE THREAD

**Issue by luclu** [dappnode/DAppNodeDocs#180]
Just wanted to let you know that https://iso.dappnode.io has a faulty redirect to the latest ISO:
https://github.com/dappnode/DAppNode/releases/download/v0.2.54/DAppNode-v0.2.54-debian-bullseye-amd64.iso (correct)
https://github.com/dappnode/DAppNode/releases/download/v0.2.54/DAppNode-v0.2.50-debian-bullseye-amd64.iso (actual)
(version number in filename is faulty)

**Comment by alexpeterson91** [comment]
Thanks for bringing this to our attention!

**Comment by tropicar** [comment]
Fixed
