### ISSUE TITLE
Install link in the README is broken

### ISSUE THREAD

**Issue by radkomih** [dappnode/DAppNodeDocs#206]
**Describe the bug**

Inside the [README section](https://github.com/dappnode/DAppNode#get-dappnode), the [Install DAppNode on your host machine](https://docs.dappnode.io/install/) link is broken.

**To Reproduce**

1. Click the [Install DAppNode on your host machine](https://docs.dappnode.io/install/) link
2. You get this screen [See error-->](https://docs.dappnode.io/install/)

**Expected behavior**

**Screenshots**

**DAppNode version:**

**Additional context**

**Comment by eduadiez** [comment]
@tropicar could you check this?

**Comment by tropicar** [comment]
Fix here https://github.com/dappnode/DAppNode/pull/500
