### ISSUE TITLE
How to connect to your DAppNode VPN

### ISSUE THREAD

**Issue by FewtureFinance** [dappnode/DAppNodeDocs#232]
http://my.dappnode/#/vpn/wireguard

Learn more about VPN at: [How to connect to your DAppNode VPN](https://docs.dappnode.io/user-guide/ui/access/vpn)

Link is broken

**Comment by alexpeterson91** [comment]
our documentation was all updated 6 days ago, and we're still finishing up editing the links in the UI but we just published a release with the new links to some of the docs since the new docs were published this week.  This will be fixed for the next release, thanks for the report!

**Comment by pablomendezroyo** [comment]
documentation refactored
