### ISSUE TITLE
Crowdin link doesn't work

### ISSUE THREAD

**Issue by wimel** [dappnode/DAppNodeDocs#235]
Trying to help the Spanish-speaking community I have found that the link to Crowdin doesn't work.

When you go to [documentation](https://docs.dappnode.io/) and "English>Help Us Translate"  in the part of [Project Overview](https://docs.dappnode.io/help-us-translate#project-overview) and clic on [Access our Crowdin project here](https://crowdin.com/project/dappnodedocs) it looks like the link is broken or the repository is not accessible.
Thanks for your work!!

**Comment by pablomendezroyo** [comment]
we will re-implement crowdin in the new documentation

Closed by https://github.com/dappnode/DAppNodeDocs/issues/193
