### ISSUE TITLE
Missing Page

### ISSUE THREAD

**Issue by tjayrush** [dappnode/DAppNodeDocs#250]
From your own "recover password" page on the dAppNode login screen. It links to here:

https://docs.dappnode.io/user-guide/support/troubleshooting#recover-ui-password

Which produces a missing page error.

**Comment by pablomendezroyo** [comment]
Closed by https://github.com/dappnode/DAppNodeDocs/issues/236#issuecomment-1733293744 

You can find the new docu link at https://docs.dappnode.io/docs/user/getting-started/choose-your-path
