### ISSUE TITLE
New documentation tree

### ISSUE THREAD

**Issue by dsimog01** [dappnode/DAppNodeDocs#261]
The new documentation will follow this tree:

1. User docs
2. Dev docs
3. Smooth
4. DAO (show warning about deprecation or remove)

Inside user docs we should include:
1. Get started
    a. Access Dappnode (via WiFi)
    b. Set up
        Register
        Repository (IPFS + Ethereum)
        Host password
        WiFi password
    c. Discover the features:
        Become a validator
        Install blockchain node packages
        ....
5. Access my Dappnode
    a. WiFi
    b. VPN (local and remote)
    c. Local (recovery)
    d. ssh (advanced)
6. Install Dappnode
    a. ISO
    b. script
7. Staking
    a. Solo staking:
        Network
        Clients
        Signer
        MEV Boost
        Smoothing Pool
    b. Rocketpool
    c. Stakehouse
    d. Stakewise (when published)
8. Videos & Tutorials
9. FAQs (get the ones we already have from Discord)
10. Packages (highlight some like HOPR)
11. Ethical Metrics

We should also:
1. Embed videos everywhere they are needed
2. Show highlighted items in documentation index
3. Enable contributions and make it easy for anybody to add new information
4. Be very verbose in clients and speak about the diversity

**Comment by pablomendezroyo** [comment]
Completed!
