### ISSUE TITLE
Add IPFS FAQs

### ISSUE THREAD

**Issue by dappnodedev** [dappnode/DAppNodeDocs#314]
We can add new IPFS FAQs (which could be placed in repository or in a specific page for IPFS)

1. You are not able to install a package and you get errors like:
```
ERROR [../../../file:/usr/src/app/packages/dappmanager/src/daemons/autoUpdates/updateMyPackages:64] Error checking web3signer-lukso.dnp.dappnode.eth version Error: resolver or addr is not configured for ENS name (argument="name", value="web3signer-lukso.dnp.dappnode.eth", code=INVALID_ARGUMENT, version=contracts/5.7.0)
```

Solution: Check the IPFS mode in repository, verify the IPFS package is running (if local), set a valid IPFS gateway (if remote), try to switch the mode....

2. The IPFS package is restarting:

Solution: Have a look at the IPFS logs, you might see an error during a database version migration. This issue can probably be solved by removing IPFS package volumes, upgrading to a newer version of the IPFS package or both.

3. Packages in the Dappstore or in the Stakers tab are not loading:

Solution: Same as number 1

**Comment by pablomendezroyo** [comment]
Agree! it would help a lot in terms of support!
