### ISSUE TITLE
Add local proxy docs

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodeDocs#40]
This PR https://github.com/dappnode/DNP_DAPPMANAGER/pull/783 adds a view that references https://docs.dappnode.io/connect/#via-local-proxy

There must exist docs there before the DAPPMANAGER release. If you want to change the URL or title of the section, please do it and then do a PR to the DAPPMANAGER

**Comment by tropicar** [comment]
fix https://github.com/dappnode/DAppNodeDocs/pull/41
