### ISSUE TITLE
Custom Hardware link is broken

### ISSUE THREAD

**Issue by winksaville** [dappnode/DAppNodeDocs#59]
The "Custom Hardware" link is broken

In the "Custom Hardware" section the "Custom Hardware", https://docs.dappnode.io/get-started/installation/introduction/introduction, link on the "Introduction" page, https://docs.dappnode.io/get-started/installation/introduction, and it yeilds:

"Oh oh... You probably weren't looking for this.
We've changed the documentation to serve you better and we might have broken this link.

If you got here following one of our links, please report the broken link here.

Back to homepage"

Also in the "Arm Hardware" section the "Custom Hardware", https://docs.dappnode.io/get-started/installation/introduction/arm-hardware/hardware-recommendations, yields the same 404 as above.

**To Reproduce**

1. Click on https://docs.dappnode.io/get-started/installation/introduction/introduction

or 

1. Click on https://docs.dappnode.io/get-started/installation/introduction/arm-hardware/hardware-recommendations

**Expected behavior**

Both should go to the real "Custom Hardware" page

**Comment by winksaville** [comment]
I just found the probable correct links from the left "toc" panel:

This probably fomr the first "Custom Hardware": https://docs.dappnode.io/get-started/installation/custom-hardware/hardware-recommendations. And this for the second one in Arm Hardware, https://docs.dappnode.io/get-started/installation/arm-hardware/hardware-recommendations.

**Comment by tropicar** [comment]
It's fixed. Thank you very much for the feedback
