### ISSUE TITLE
Local Proxy link broken

### ISSUE THREAD

**Issue by PagziTechInc** [dappnode/DAppNodeDocs#88]
https://docs.dappnode.io/get-started/installation/custom-hardware/installation/iso/

Local Proxy link at bottom is pointing to : https://docs.dappnode.io/get-started/user-guide/ui/access/local-proxy

Oh oh... You probably weren't looking for this.

**Comment by tropicar** [comment]
It's fixed, if you from that link now works, you are redirected to https://docs.dappnode.io/user-guide/ui/access/local-proxy/
